name: Build vscode server
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "git commit:"
        default: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    # env:
    #   arch: ${{ github.event.inputs.target_arch }}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     node_version: [18.17.1]
    #     android_sdk_version: [24]
    #     target_arch: [arm64]

    steps:
      - uses: actions/checkout@main
      - name: Install build dependencies
        run: |
          node -v
          sudo apt update
          sudo apt install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3
          yarn global add node-gyp

      - name: Fetch source code
        run: |
          # git clone https://github.com/gitpod-io/openvscode-server --depth=1
          curl -Lk https://github.com/microsoft/vscode/archive/${{ github.event.inputs.commit }}.tar.gz | gzip -d | tar -xv
          mv vscode-${{ github.event.inputs.commit }} vscode

      - name: Build
        working-directory: vscode
        run: |
          yarn

          ## Server
          yarn gulp compile
          yarn gulp node

          ## Web
          yarn gulp compile
          yarn gulp compile-web
          # ./script/code-server.sh

      - uses: actions/upload-artifact@main
        with:
          name: github_actions_upload_artifact_raw
          path: echo_hello

      - uses: actions/upload-artifact@main
        with:
          name: github_actions_upload_artifact_gzip
          path: echo_hello.tar.gz

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.4
        with:
          retain_days: 0
          keep_minimum_runs: 1

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          # Artifact name
          name: debian-rootfs-${{ github.event.inputs.dist_version }}-${{ github.event.inputs.target_arch }}
          # Path to the file to upload
          path: debian-rootfs-${{ github.event.inputs.dist_version }}-${{ github.event.inputs.target_arch }}.tar.gz
          # secrets.GITHUB_TOKEN
          repo-token: ${{ secrets.GITHUB_TOKEN }}
