name: Build llvm
run-name: Build llvm ${{github.event.inputs.tag}}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag:"
        default: "llvmorg-18.1.1"
        required: true

jobs:
  build-llvm:
    runs-on: ubuntu-latest
    # env:
    #   arch: ${{github.event.inputs.msg}}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     target_arch: [matrix0, matrix1]
    env:
      ZIG_VERSION: 0.11.0

    steps:
      - name: Checkout llvm-project
        uses: actions/checkout@v4.1.1
        with:
          repository: llvm/llvm-project
          ref: ${{github.event.inputs.tag}}
          fetch-depth: 1

      - name: Create zig wrapper
        run: |
          cat <<-'EOF' >zig_wrapper
          #!/bin/sh
          set -eu

          if test -h "$0" && ! test "$(basename "$(readlink "$0")")" = "$(basename "$(readlink -f "$0")")"; then
            BIN=$(readlink "$0") && cd "$(dirname "$0")" && "${BIN}" "$@"
          else
            WRAPPER="$(basename "$0")"
            case "${WRAPPER}" in
            ar | cc | c++ | dlltool | lib | ranlib | objcopy | ld.lld)
              set -- "${WRAPPER}" "$@"

              ## Zig doesn't properly handle these flags so we have to rewrite/ignore.
              ## None of these affect the actual compilation target.
              ## https://github.com/ziglang/zig/issues/9948
              case "${WRAPPER}" in
              cc | c++)
                for argv in "$@"; do
                  case "${argv}" in
                  -Wp,-MD,*)
                    set -- "$@" "-MD" "-MF" "$(echo "$argv" | sed 's/^-Wp,-MD,//')"
                    ;;
                  -Wl,--warn-common | -Wl,--verbose | -Wl,-Map,*) ;;
                  *)
                    set -- "$@" "${argv}"
                    ;;
                  esac
                  shift
                done
                ;;
              esac
              ;;
            *)
              printf "Usage:\nln -s zig_wrapper [cc|c++|dlltool|lib|ranlib|objcopy|ld.lld]\n" >&2
              exit
              ;;
            esac

            # echo ${WRAPPER_BIN} "$@"
            "${ZIG-zig}" "$@"
          fi
          EOF
          chmod +x zig_wrapper

          mkdir -p bin
          for tool in cc c++ dlltool lib ranlib objcopy ld.lld; do
            ln -snf ../zig_wrapper bin/${tool}
          done

      - name: Get zig
        run: |
          curl -Lk https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz | xz -d | tar -x
      
      - name: Build
        run: |
          sudo apt install ninja-build
          export ZIG=${PWD}/zig-linux-x86_64-${ZIG_VERSION}/zig
          export CC=${PWD}/bin/cc
          export CXX=${PWD}/bin/c++

          mkdir build && cd build
          TARGET=aarch64-linux-musl
          cmake \
            ../llvm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang;" \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            -DLLVM_HOST_TRIPLE=${TARGET} \
            -G "Ninja"

          cmake --build .

          tree bin
          file bin/*

      - name: xz package
        run: |
          mv bin clang+llvm-18.1.1-aarch64-linux-musl
          tar -c clang+llvm-18.1.1-aarch64-linux-musl | xz -T0 > clang+llvm-18.1.1-aarch64-linux-musl.tar.xz

      - name: Upload release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: "llvm"
          artifacts: clang+llvm-18.1.1-aarch64-linux-musl.tar.xz
          allowUpdates: true
          replacesArtifacts: true
          body: |
            [action](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
