name: Build vscode server
run-name: Build vscode server commit:${{ github.event.inputs.commit }}
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "git commit:"
        default: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tasks: [vscode-reh-linux-x64-min, vscode-reh-linux-arm64-min, vscode-reh-web-linux-alpine-min, vscode-reh-web-alpine-arm64-min]

    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          node -v
          sudo apt update
          sudo apt install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3
          yarn global add node-gyp

      - name: Fetch source code and patch
        run: |
          git clone https://github.com/microsoft/vscode
          cd vscode
          git checkout ${{ github.event.inputs.commit }}

      - name: Build
        working-directory: vscode
        run: |
          ## Install dependencies ====
          ## Electron and browsers are not required
          ## for code-server build.
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

          yarn
          yarn gulp ${{ matrix.tasks }}

      - name: Test output
        run: |
          tree -L 1
          find vscode-reh-web-linux-x64 -name "workbench.web.main.js" -exec head -n3 {} \;

      - name: Package
        run: |
          find -maxdepth 1 -name "vscode-*" -type d | while IFS= read -r dir; do
            tar -c "${dir}" | xz -T0 > "${dir}".tar.xz
          done

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.tasks }}
          path: vscode-*

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.4
        with:
          retain_days: 0
          keep_minimum_runs: 1

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          # Artifact name
          name: debian-rootfs-${{ github.event.inputs.dist_version }}-${{ github.event.inputs.target_arch }}
          # Path to the file to upload
          path: debian-rootfs-${{ github.event.inputs.dist_version }}-${{ github.event.inputs.target_arch }}.tar.gz
          # secrets.GITHUB_TOKEN
          repo-token: ${{ secrets.GITHUB_TOKEN }}
