name: Template
on:
  push:
    paths: ".github/workflows/template.yaml"
  workflow_dispatch:

jobs:
  job1:
    name: "job1"
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: |
          pwd
          df -h
          nproc --all
          cat /proc/cpuinfo
