name: Template
on:
  push:
    paths: ".github/workflows/template.yaml"
  workflow_dispatch:

jobs:
  template_job:
  name: Template job
  runs-on: ubuntu-latest

  - steps:
    - name: Task 1
      run: |
        pwd
        df -h
        nproc --all
        cat /proc/cpuinfo