name: Template
on:
  push:
    paths: ".github/workflows/template.yaml"
  workflow_dispatch:

jobs:
  job1:
    name: "job1, build ${{matrix.target}}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "aarch64-linux-musl"
          - "arm-linux-musleabi"
          - "x86-linux-musl"
          - "x86_64-linux-musl"

    steps:
      - name: step1
        run: |
          pwd
          df -h
          nproc --all
          cat /proc/cpuinfo
